### ISSUE TITLE
dogwater/waterline

### ISSUE THREAD

**Issue by moklick** [jedireza/frame#103]
Hello,

did you thought about using an ORM like [waterline](https://github.com/balderdashy/waterline) for frame in order to support different database types? There is also an hapi plugin called [dogwater](https://github.com/devinivy/dogwater).

**Comment by jedireza** [comment]
Thanks for opening an issue.

Yes I've seen these types of ORMs and chose not to use them. [`hapi-mongo-models`](https://github.com/jedireza/hapi-mongo-models/) was made at the same time as Frame and I haven't re-approached the idea of using other data layers since then.
