### ISSUE TITLE
$unset resetPassword field with 'undefined' produces 500 error

### ISSUE THREAD

**Issue by Kyii** [jedireza/frame#104]
hey jedireza, 

i think there is a small bug with resetting the password in server/api/login.js.

    $unset: {
        resetPassword: undefined
    }

this will give you:

    MongoError: exception: '$unset' is empty. You must specify a field like so: {$mod: {<field>: ...}}

maybe since mongodb 2.6 you can't use `undefined` here. but  `null, '', and {}` will successfully remove the the resetPassword field after the password has been changed. if that was the intended behavior.

**Comment by Kyii** [comment]
i use mongodb 2.6.5

**Comment by jedireza** [comment]
Thanks for opening an issue. I haven't had a lot of time to check this out yet. Would you be willing to create a PR to fix these cases?

**Comment by GlennGeenen** [comment]
I just tested this with mongodb 3.0.4 and I don't have this problem.
The Mongo docs say:
> The specified value in the $unset expression (i.e. "") does not impact the operation.

**Comment by jedireza** [comment]
I just tested this and didn't get an error.
