### ISSUE TITLE
No directions on how to login using Postman

### ISSUE THREAD

**Issue by bartonhammond** [jedireza/frame#108]
Wiki only states that once you login you'll see a json response.  But how do you use Postman to make the login request?  Please be specific.

**Comment by jedireza** [comment]
Thanks for opening an issue. From the wiki page:

> By default Frame uses basic authentication. As a convenience, we include an `authHeader` property. You can use this value to create an `Authorization` header for future requests. The `session._id` and the `session.key` properties make up the `username` and `password` parts of the basic authentication credentials.

> _For more details on how basic authentication works see [this wikipedia page](http://en.wikipedia.org/wiki/Basic_access_authentication)._

**Comment by bartonhammond** [comment]
Weird you think that those directions have anything to do w/ actually creating the login request using Postman.  You must believe everyone is born with the knowledge of how to use Postman.

**Comment by jedireza** [comment]
Oh haha. Point taken. I've added a link to the postman docs about making requests. (http://www.getpostman.com/docs/requests)

Keep in mind, Postman is just a GUI tool, you could use `curl` on the command line too if you so desired.

Thanks for posting and getting involved.
