### ISSUE TITLE
Session timeout

### ISSUE THREAD

**Issue by kole** [jedireza/frame#124]
Unless I'm just not seeing it in the configs, there is no session timeout management.

I feel like there should be a default session timeout built in to this, no?

**Comment by jedireza** [comment]
Correct, this isn't built-in. What do you think is a good default?

**Comment by kole** [comment]
I suppose there are 2 different ways to look at this. Is this intended to support 'client' sessions or 'user' sessions? 

For client sessions (think Twitter clients like Tweetbot), I'd say the timeout should be something like 24 hours or 7 days or something like that.

For user sessions (think Twitter users like @BrendanEich), I'd say the timeout should be something like 30-60 minutes.

Since this project employs unrestricted signups (not moderated/controlled), it seems like this is probably more of a user session scenario... but I'm curious as to what your intent was in creating this.

**Comment by jedireza** [comment]
Sorry for the unintended ping Brendan.

> Is this intended to support 'client' sessions or 'user' sessions?

Yup. Good question. That's up to the person taking a copy of Frame.

Frame is a minimal boilerplate. Once you take a copy and run with it, it's all yours. There's a balance between the core user system api and being unopinionated in cases like session timeouts, email verification, 3rd party logins, etc...

Like those other cases, I don't think this should be built-in by default. In these cases I do encourage people to write up a wiki page though. Let me know if you add a new page for that.

**Comment by kole** [comment]
@jedireza Not sure I understand. This would have to be built, right? This isn't just a simple config update for functionality that already exists? 

It seems like this issue should be open until the functionality exists and then a wiki page can be written to talk about different configuration options for different requirements.

**Comment by jedireza** [comment]
> This would have to be built, right? This isn't just a simple config update for functionality that already exists?

Correct. The same as anything else not included by default (email verification / 3rd party login).

> It seems like this issue should be open until the functionality exists

We can update this thread with updates if/when they exist.
