### ISSUE TITLE
Babel support

### ISSUE THREAD

**Issue by lolmaus** [jedireza/frame#126]
Want to use this: https://www.npmjs.com/package/babel-preset-node5

**Comment by jedireza** [comment]
Thanks for creating an issue. This isn't something I think should be added to Frame by default.

**Comment by lolmaus** [comment]
It's not only about async/await. 

There are more features that Node does not support: decorators, destructuring, classes, rest/spread, trailing function commas, import/export, sticky regex, unicode regex...

I just can't imagine writing my JS without destructuring and rest/spread. It makes no sense in 2016.
