### ISSUE TITLE
Login trouble

### ISSUE THREAD

**Issue by sirEgghead** [jedireza/frame#128]
Hey, thanks for all your hard work.  I've looked over several of your projects, and I love the work you do!

I’m having trouble logging in.  I’m used to using Postman.  I even used Postman to successfully send a password reset key and then reset the password.

Attached is a screenshot of my results of trying to login.  Am I doing something wrong?  I've looked over your wiki and also at the closed issue where someone else needed help logging in.

![screenshot_83](https://cloud.githubusercontent.com/assets/6648625/14087329/712c0750-f4f7-11e5-8343-33bc111ece0a.png)

**Comment by sirEgghead** [comment]
Nevermind.  Call me an idiot.  :)

I sent username and password as body and I received the session ID.  However, I have to say that I'm not fond of the password over plain text.  Am I missing something there?

**Comment by jedireza** [comment]
Glad you got it worked out.

> I sent username and password as body and I received the session ID. However, I have to say that I'm not fond of the password over plain text.

Ideally you'd be connecting to a secure endpoint, preventing this data from being sent in the open. Keep in mind, even though the authorization header gets base64'd, it's still plain text unless your endpoint is secure.
