### ISSUE TITLE
Setup script duplicates

### ISSUE THREAD

**Issue by sirEgghead** [jedireza/frame#129]
Hey, great work on your project!

I just wanted to let you know of a small issue that I found.  When running the setup script, you get duplicate defaults listed.  See screenshot for explanation.  I found where to fix it in my personal setup.js file as well.  I could pass that info on to you if you like.

Thanks again!

![screenshot_84](https://cloud.githubusercontent.com/assets/6648625/14087562/8e9b1e2e-f4f8-11e5-8c16-16c2763bf3df.png)

**Comment by jedireza** [comment]
Thanks for reporting this. Must be from updates to [`promptly`](https://github.com/IndigoUnited/node-promptly).

**Comment by sirEgghead** [comment]
You the man. :)
