### ISSUE TITLE
Runnning Test fails with Multiple callbacks issues.

### ISSUE THREAD

**Issue by saurabhghewari** [jedireza/frame#131]
Cloned the repo, and followed the instructions as specified in readme.md. All runs fine. But running test throws error with
"Multiple callbacks or thrown errors received in test "App it composes a server" (done)".
I can't find it why this is throwing error. Is this related to registering the user developed plugins?

**Comment by jedireza** [comment]
Thanks for opening an issue.

I just updated the dependencies, did a fresh install and ran the tests. All is good. If you've added your own plugins they could very well contribute to failing tests.

**Comment by jedireza** [comment]
I'm closing for now. Feel free to open another issue if/when you have more details about the error.

**Comment by saurabhghewari** [comment]
Thanks for the reply. But, I am just referring it to develop plugins, Glue composing method etc. I haven't added my own plugin to it. I will post an image of error.
