### ISSUE TITLE
npm run setup @ windows 10 not working

### ISSUE THREAD

**Issue by MarcusSpecht** [jedireza/frame#133]
npm run setup

> frame@8.0.0 setup C:\Users\XXX\XXX\XXX\frame
> ./setup.js

Der Befehl "." ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "setup"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! frame@8.0.0 setup: `./setup.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frame@8.0.0 setup script './setup.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the frame package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./setup.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs frame
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls frame
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\XXX\XXX\XXX\frame\npm-debug.log

**Comment by MarcusSpecht** [comment]
`node setup.js` instead of `npm setup` worked

**Comment by jedireza** [comment]
Thanks for opening an issue. Yup, the [setup script in `package.json`](https://github.com/jedireza/frame/blob/674cefb9bff0a79196b45577bd261c566695cfde/package.json#L7) should change to `node setup.js` instead of just `./setup.js`.

**Comment by jedireza** [comment]
This will get resolved when I update #141 since the first time setup script has changed. Closing this issue for now.
