### ISSUE TITLE
Initial setup allows you to bypass User schema validation?

### ISSUE THREAD

**Issue by dwangus** [jedireza/frame#134]
I noticed that in setup.js, you can directly call User.create(...), and in the /server/models/user.js, there's nothing stopping a root user from having incorrectly formatted fields in the Mongo database?

**Comment by jedireza** [comment]
Thanks for opening an issue. You're correct, a similar question was asked before; ["Should model validation happen by default?"](https://github.com/jedireza/frame/issues/98)
