### ISSUE TITLE
Request creation of a tutorial

### ISSUE THREAD

**Issue by entrptaher** [jedireza/frame#136]
This is related to an issue posted in drywall, but it was less informative. https://github.com/jedireza/drywall/issues/378

So, the request is this,

Can we hope that there will be any good tutorial or some quick workaround to show people how they can add their own things to frame/aqua/drywall? Its deeply related to any framework.

For example, such situations,
 - User wants to add a field called *favorite food* in the framework? So that it can be shown in admin panel.
 - User wants to show this field *favorite food* in the home page after login.
 - User wants to see their *favorite food* after login instead of the admin panel with clock.

I used favorite food as example, but it can be just anything. No one knows this framework better than you, so I just thought it would be best if you could share such small tutorials with us so if we ever want, we could link others to these tutorials.
And, its an issue with documentation (quick start). If I could be of help, I'd glad to. But there should be a starting point at least.

Thanks.

**Comment by jedireza** [comment]
Thanks for opening an issue.

> Can we hope that there will be any good tutorial or some quick workaround to show people how they can add their own things to frame/aqua/drywall? Its deeply related to any framework.

These (Drywall/Frame/Aqua) are boilerplate apps, not frameworks. They're starting points which use other frameworks and modules. Express is a framework, hapi is a framework and the both have great documentation.

> And, its an issue with documentation (quick start). If I could be of help, I'd glad to. But there should be a starting point at least.

One should be able to accomplish the "favorite food" examples you mention above by following the documentation of the frameworks and modules we use and following the code paths. A developer using these boilerplates really do need to be comfortable reading the code, debugging and finding relevant documentation to accomplish their goals.

With that said, the wiki is open and I'm happy to review any guides/tutorials you (or others)  create and/or link to blog posts.
