### ISSUE TITLE
Custom groups

### ISSUE THREAD

**Issue by dmitrypo** [jedireza/frame#139]
Hello, 

Also I have the same question about groups.
For example I would like to make some custom groups for accounts or another custom role. It's different level of abstractions as I understand.
Something like this:

"Town1-District1"... "Town1-District999",
"Town2-District1"..."Town2-District999",...etc. 

And put users in different groups. Maybe in some cases users will be in several groups at the same time.
How can I achieve this results? Through API or another way?
And with roles it give me excellent result.

Other words I will have 100500 users with 2-5 roles (In my bussines perspective) and ~100500/10 groups with another bussines perspective.

Could you please advise me? 

Thanks,
Dmitry

**Comment by jedireza** [comment]
I'm not following the need exactly.

**Comment by dmitrypo** [comment]
Ok, I see that looks like be extended in account code for groups can be possible. And also the same if it will be my custom role.

**Comment by jedireza** [comment]
Correct. Can this issue be closed now?

**Comment by dmitrypo** [comment]
Sure! Thanks for your assisance!
