### ISSUE TITLE
UnhandledPromiseRejectionWarning 

### ISSUE THREAD

**Issue by bmgdev** [jedireza/frame#145]
I get this on fresh install of latest version:

(node:28352) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): MongoError: no such cmd: createIndexes

**Comment by bmgdev** [comment]
btw im running mongo 2.49 - it sounds like mongo 2.6 is necessary for autoindex?

"mongodb": "2.x.x", listed in package

**Comment by jedireza** [comment]
Thanks for opening an issue.

I also get the unhandled promise rejection. This is new as of `node@6.6.x` ([changelog](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#2016-09-14-version-660-current-fishrock123)).

I believe this is from a dependency and not from Aqua's code base. I haven't dug into these warnings yet. If you (or anyone reading) finds out this can be fixed within Aqua please open an issue and/or PR.

> btw im running mongo 2.49 - it sounds like mongo 2.6 is necessary for autoindex?

The `autoIndex` settings you see in the [`manifest.js`](https://github.com/jedireza/aqua/blob/3a00d782d4c053583ef0a4e1a481ee6d49f2eac3/manifest.js#L80) is [consumed by the `hapi-mongo-models`](https://github.com/jedireza/hapi-mongo-models/blob/7d8a4837ca8ecd7fedb96ab9f0d4595fcc34199b/index.js#L41-L48) plugin, which simply calls `createIndexes` on the collection directly.
