### ISSUE TITLE
Support for social media login?

### ISSUE THREAD

**Issue by tarekshumaila** [jedireza/frame#146]
Looks like this is what am looking for. I used drywall before and it was great, however I wanted to move away from jade and go into angular and this looks like a perfect starting point. Does this starter support social media logins?

**Comment by jedireza** [comment]
Thanks for opening an issue.

I've left third-party authentication out of Aqua to keep things simple and easier to maintain.

Checkout [`hapijs/bell`](https://github.com/hapijs/bell), a third-party authentication plugin for hapi.

**Comment by bmgdev** [comment]
@jedireza I noticed your thread here:  https://github.com/hapijs/bell/issues/30  and am curious as to what state that branch is in.  Is it usable?  

If not, has anyone else integrated Bell with Frame yet?
