### ISSUE TITLE
app crashes after 'first-time-setup' run

### ISSUE THREAD

**Issue by tarekshumaila** [jedireza/frame#147]
Hi again, 

Sorry to bother you again. I am getting the below message after I ran the setup.

[nodemon] restarting due to changes...
[nodemon] starting `node --inspect server.js`
node: bad option: --inspect
[nodemon] app crashed - waiting for file changes before starting...

Node modules are installed with npm install. Mongodb is running on MongoLab. 

I looked in the previous issues, didnt find anything related to this from the topics.  Maybe it is something specific to my Mac osx. Please let me know if there is a fix for this as I want to build an app with this framework but am not getting into a good kickstart.

**Comment by tarekshumaila** [comment]
![screen shot 2016-09-28 at 8 38 22 pm](https://cloud.githubusercontent.com/assets/6101167/18939153/978e9c64-85bb-11e6-8212-1a3b759bba91.png)

Webstorm doesnt like this file and marked it with lots of red syntax errors, not sure why. It does that everytime I try to use the '=>' anywhere.

**Comment by bmgdev** [comment]
You need to be running node 6 to use --inspect

**Comment by tarekshumaila** [comment]
oh looks like am using v4.4.5 

am rusty, I'll update and see if that fixes it

**Comment by bmgdev** [comment]
Or don't run with --inspect.

**Comment by tarekshumaila** [comment]
updated to 6.6, now am getting this:


[nodemon] 1.10.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --inspect server.js`
Debugger listening on port 9229.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/remote/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=localhost:9229/node
/Users/shebatech/projects/frame-hapi/node_modules/bcrypt/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/shebatech/projects/frame-hapi/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/shebatech/projects/frame-hapi/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:556:32)
Waiting for the debugger to disconnect...

-----------


I go to http://localhost:9000/ and site cant be reached :/

**Comment by jedireza** [comment]
You may need to `$ npm rebuild` since you changed node versions.

https://docs.npmjs.com/cli/rebuild

**Comment by tarekshumaila** [comment]
up and running.. thank you so much.
