### ISSUE TITLE
JWT support

### ISSUE THREAD

**Issue by schengnz1** [jedireza/frame#148]
From briefly reading the code, Frame supports cookie-based session. We are looking to use JSON Web Token (JWT) instead of cookie. 

If I understand the code correctly, Frame currently does not support JWT. What does it take to add JWT support, and how doable/easy is it?

Thanks.

**Comment by jedireza** [comment]
Thanks for opening an issue.

Frame is actually using [basic http authentication by default](https://github.com/jedireza/frame/blob/bdc3366a911039bcadc605fe809479f568bcf7f6/server/auth.js#L14). With [Aqua](https://github.com/jedireza/aqua) though, I went with cookies.

You can swap out strategies pretty easily. Once you add or replace the strategy in `server/auth.js`, all you need to do is [update the config for the route handlers](https://github.com/jedireza/frame/blob/bdc3366a911039bcadc605fe809479f568bcf7f6/server/api/accounts.js#L23).

Do let me know if you're willing to share your progress with JWT, maybe we could add a wiki page about it.

**Comment by bmgdev** [comment]
+1

**Comment by bmgdev** [comment]
@lostdalek really great of you to share, much appreciated as always.
