### ISSUE TITLE
Postman file

### ISSUE THREAD

**Issue by Fr4nz78** [jedireza/frame#149]
You mention Postman but unfortunately I don't think there is an exported file I could import in Postman directly. Do you have a trick to generate / update the calls from the existing documentation in Postman ? I started to manually import the calls but it feels wrong as if something change in the API it won't be valid anymore.

**Comment by jedireza** [comment]
Thanks for opening an issue.

> You mention Postman but unfortunately I don't think there is an exported file I could import in Postman directly.

I'm unaware of a file importing feature with Postman. I'm talking about this Chrome app: https://www.getpostman.com/

There is a wiki page on [How to Login](https://github.com/jedireza/frame/wiki/How-to-login) that may help.

**Comment by jedireza** [comment]
In admin > accounts there is a "create new" button in the top right, that will open a modal.
