### ISSUE TITLE
Why is server.initialize necessary?

### ISSUE THREAD

**Issue by peterorosz** [jedireza/frame#151]
Hi, I'm very new to programming and I have a very basic question. Sorry for the trouble.

In some test files (api/index.js), you use
```
if (err) {
    return done(err);
}

done();
```

and in some (web/index.js) you use
```
if (err) {
    return done(err);
}

server.initialize(done);
```
Using just `done()` in the second example results in an error. Why? What's the difference between the two tests? First, you register a couple of plugins, then you then inject a request... I just don't get it :)

Thanks for the answer!

**Comment by jedireza** [comment]
Thanks for opening an issue.

We're using `server.initialize` so we know all plugin registrations are finalized. Also see: http://hapijs.com/api#serverinitializecallback
