### ISSUE TITLE
Session.findByIdAndDelete missing?

### ISSUE THREAD

**Issue by ADumaine** [jedireza/frame#153]
In the logout and session APIs there are calls to Session.findByIdAndDelete but I am not finding that method in the Session model (or a search of the repository).

**Comment by jedireza** [comment]
Thanks for creating an issue. It's not missing. Models are [extended classes of `mongo-models`](https://github.com/jedireza/frame/blob/bdc3366a911039bcadc605fe809479f568bcf7f6/server/models/session.js#L9).

 - https://github.com/jedireza/mongo-models
 - https://github.com/jedireza/mongo-models/blob/master/API.md

**Comment by ADumaine** [comment]
Sorry, I was porting to postgres and had removed the reference to mongo-models and did not remember to look there.  Thanks for the quick response.
