### ISSUE TITLE
Frame <> Hapi Bell Integration

### ISSUE THREAD

**Issue by bmgdev** [jedireza/frame#154]
Has anyone else integrated Bell with Frame yet that you can point me at?

@jedireza I noticed your thread here: hapijs/bell#30 and am curious as to what state that your 'door-bell' branch is in. Is it usable? have you had success implementing multiple auth strategies? I'm in a position now where I have the hapi jwt2 lib implemented into frame and would like to add the bell fb and twitter strategies. Based on your thread above, doesn't seem possible to have multiple strategies?

**Comment by jedireza** [comment]
Thanks for opening an issue.

> I noticed your thread here: hapijs/bell#30 and am curious as to what state that your 'door-bell' branch is in. Is it usable?

It's pretty old. I don't remember the state I left it in.

> have you had success implementing multiple auth strategies?

I have not.

> Based on your thread above, doesn't seem possible to have multiple strategies?

I think the proposed solutions boil down to creating an endpoint (ex: `/login/twitter`) and on success of that, create a session that you can use with your other routes. I have not done this myself.
