### ISSUE TITLE
Use it as WebSocket

### ISSUE THREAD

**Issue by Tavousi** [jedireza/frame#155]
Hi there,
may i use this api with websocket ?
i think if we use web socket instead of rest we can just send one req to server for connection and then in every page we can use lots of action from api server with just one connection ! &&its realtime . what you think ?! is it good ?!
thanks

**Comment by jedireza** [comment]
Thanks for opening an issue. If you're interested in using Websockets with hapi, take a look at `nes`.

https://github.com/hapijs/nes

**Comment by Tavousi** [comment]
Ohum i saw hapijs/nes but it's possible to use Websocket on frame with little change ?!

**Comment by jedireza** [comment]
> with little change

Probably not. Stateless HTTP requests are  fundamentally different to Websockets.

**Comment by Tavousi** [comment]
Ok, sorry for lots of question , im so curious . you think wich one is better ?!

**Comment by jedireza** [comment]
> Ok, sorry for lots of question , im so curious . 

No worries. 😁 

> you think wich one is better ?!

Neither. They're made for different use cases.

HTTP is easy and ubiquitous. Easy in the sense that we can make requests from the command line (ex: `curl`, `wget`).

Websockets have more overhead. Although, they're built on-top of HTTP, connections need to be setup are state-full. Websockets are well suited for real-time/event-based applications more than [CRUD](https://en.wikipedia.org/wiki/Create,_read,_update_and_delete)/REST applications.

This article may help too:

 - https://www.pubnub.com/blog/2015-01-05-websockets-vs-rest-api-understanding-the-difference/
 - [see more google results](https://www.google.com/search?q=crud%20rest%20vs%20websockets)

**Comment by Tavousi** [comment]
thanks, links are usefull ! i got what i need 
;)

**Comment by Tavousi** [comment]
Umm and may i recode frame to use it in 2way , rest and websocket at sametime like (http://feathersjs.com) ?@! there is any way to do this ?

**Comment by jedireza** [comment]
Sure. Use `nes` to add that real-time logic.

**Comment by Tavousi** [comment]
Um, you mean after i use `nes`,  i can use rest and websocket at sametime when i start frame recoded app ? and its not needed to use frame as rest and fram2(nes) as websocket !! ?

**Comment by jedireza** [comment]
No. You'll have to code the logic for websocket connections using `nes`.

**Comment by Tavousi** [comment]
thank u, i got it ! i'm student in biomedical engineering . for hobby i wrote php for 5 years from fifteen. im profesional in php and client now . i start ES6 and nodejs from last summer and im so happy find mr Reza to ask my professional questions in this technology . in last i wish, you are more success in your life .
