### ISSUE TITLE
hashing session key

### ISSUE THREAD

**Issue by JKHeadley** [jedireza/frame#156]
Hey there! I was wondering what advantage there is to hashing the session key in the db rather than just using a random value such as the original UUID. Does it add any security? If so, could you give an example of a potential security breach that it could prevent? Thanks! Great project btw 👍

**Comment by jedireza** [comment]
Thanks for opening an issue.

The session key is essentially a password (for that session). And for the same reasons we shouldn't store passwords in plain text, my thinking is that we shouldn't store any secrets in plain text.

**Comment by JKHeadley** [comment]
Thanks for the quick response! 

That's logical reasoning.  Your answer led me to look deeper into why passwords themselves should be hashed, and I've found two main reasons.  One which seems relevant to the session situation and one that doesn't.

1. Hashing passwords prevent attackers with db read access from acquiring user's passwords, which is generally considered very sensitive personal data and is commonly used in other systems as well as the current system. This doesn't necessarily apply to our session key since it is specific to our system and not necessarily "sensitive personal" information.

2. Hashing passwords prevents attackers with db **read only** access from acquiring information to "elevate" their access to the db by authenticating to the server.  This does apply to the session key since anyone with a valid session id and key can authenticate to the server.

Mostly just writing out my thoughts here. If you have any thoughts to add I'd love to hear it. Thanks again!

**Comment by jedireza** [comment]
> Mostly just writing out my thoughts here. If you have any thoughts to add I'd love to hear it. Thanks again!

👍 love this, thanks!
