### ISSUE TITLE
Around MongoDB

### ISSUE THREAD

**Issue by Tavousi** [jedireza/frame#157]
Hi, i read hapi in action and i understand frame very well now but the last question is about nosqls ! we try t make website for ~5m users ! its a video sharing platform . we ask you about nosql and mongo ! can we use it for a big project and we will need to analyze our DB in real time so we choice nosql but is mongo ready for use in this project or not yet ?! and you chose wich one mongodb as nosql or mysql as sql !
wich one is better for a big project like youtube ?!
thanks

**Comment by jedireza** [comment]
Thanks for opening an issue. 

> is mongo ready for use in this project or not yet ?!

This is really up to you and is heavily influenced by your design choices. https://www.mongodb.com/mongodb-scale

>  and you chose wich one mongodb as nosql or mysql as sql ! wich one is better for a big project like youtube ?!

I'm not sure. I'd probably use Postgres over MySQL these days, but again this all depends on you. In the end you have to maintain your deployment.

- - - -

As a side note I've read some good things about RethinkDB for real-time applications. I've never used it myself. https://www.rethinkdb.com/
