### ISSUE TITLE
About Mongo Schema

### ISSUE THREAD

**Issue by Tavousi** [jedireza/frame#158]
Hi, ;)
i make something like this in mysql :
![2017-03-01_14-14-51](https://cloud.githubusercontent.com/assets/1410429/23456716/dbd33046-fe89-11e6-9dcd-36b5dd52f9ab.png)
and i use (users,sessions,roles) for managing my users . its clear . i made user and admin role in roles table . in frame mongodb schema in below :
![2017-03-01_14-10-36](https://cloud.githubusercontent.com/assets/1410429/23456865/76f6abb6-fe8a-11e6-96f7-119b178761df.png)
but why we have (admin,admins,user,name,groups,admingroups and accounts) collections !?
is it a relation or embedding design ?

**Comment by jedireza** [comment]
Thanks for opening an issue.

I'm not sure where the 'name' collection you mention comes from. It's not from this project.

Also MongoDB isn't a relational database and so the data isn't normalized.

**Comment by Tavousi** [comment]
im looking for a book or good reference for learn mongodb or nosql schema designing ! have you something to read ?! (also i have mongodb in action pdf but im not started yet)

**Comment by jedireza** [comment]
I generally find tutorials online. These may be helpful:

 - https://university.mongodb.com/
 - https://www.mongodb.com/compare/mongodb-mysql
 - https://docs.mongodb.com/manual/reference/sql-comparison/

 - https://www.google.com/search?q=mongodb%20101
 - https://www.google.com/search?q=mongodb%20tutorials

**Comment by Tavousi** [comment]
Thank you so much .
