### ISSUE TITLE
Use js embeded in template

### ISSUE THREAD

**Issue by Tavousi** [jedireza/frame#160]
Hi,
& im so glad to open this issue ;)
im using this option in frame : 
`engines: { html: 'handlebars' },`
because i hate jade engine and now im looking for a way to use js in .html template like this : <% JS %> . i see, jade had something like that but in handlebars its not working !
F1 me ?!

**Comment by jedireza** [comment]
I don't think Handlebars supports embedded JavaScript. I suggest reading the docs: http://handlebarsjs.com/

**Comment by Tavousi** [comment]
Um thanks i find ejs.
