### ISSUE TITLE
Plugin for auth with server

### ISSUE THREAD

**Issue by iraniamir** [jedireza/frame#161]
cont me = requre('jedireza').KnowledgeDB;
im trying to make client with another hapijs app and im using frame as server . for auth between this two app what am i should to do ?! [ i think i must add token from server /login to my cookie with jquery when my req is recvied, is it right ?! ] [ there is any plugin for this ? ] [ in my client app i use hapijs + ejs template engine + jQeary for my client-side ] [ jQeary just send forms to server and get details, client app send all req from client-side with my simple client framework ] [ there is any app sample in github for me ] [ ?! ]
Thanks

**Comment by jedireza** [comment]
Thanks for opening an issue. I'm really not sure. If you want to communicate from one hapi app to another, you'll need to fulfill the authentication requirements configured.

**Comment by iraniamir** [comment]
Um im replace hapi-auth-basic with hapi-auth-cookie like aqua and everything is work now !
thanks any way
