### ISSUE TITLE
Best practice on managing frame integration with own front-end

### ISSUE THREAD

**Issue by jvduf** [jedireza/frame#162]
@jedireza great work on `aqua` and `frame`! I'd love to give `frame` a go and build a front-end using Vue.js on it. I was wondering if you have any best practices on how to integrate `frame` into my own project. Should I for example fork this repo and start building on top of it pulling/merging in updates from this repo? How do you approach this with `aqua`?

**Comment by jedireza** [comment]
Thanks for opening an issue.

> Should I for example fork this repo and start building on top of it pulling/merging in updates from this repo? How do you approach this with aqua?

With Aqua, I took Frame and built on top of it. I'd just fork this repo and start committing on top of it or if you'd rather not have the commit history, you could clone the repo, delete the `.git` folder and then `$ git init` and start the history from scratch.

Please do share your progress, I'd like to see what you come up with. 👍

**Comment by jvduf** [comment]
Great thanks! It's going to be a hobby project so let's see where it will go! Once I have something - I'll let you know.
