### ISSUE TITLE
SaaS and MySql / Posgresql

### ISSUE THREAD

**Issue by Alber70g** [jedireza/frame#165]
Hi,
At first look at this project it seems to be able to build a SaaS upon this, although mult-tenancy isn't really incorporated in this, at first glance. Is it a use case which is viable? 
Second question: is it possible to use MySql or Postgres or another RDBMS instead of MongoDb?

**Comment by jedireza** [comment]
> Is it a use case which is viable?

Anything is viable if you put your mind to it.

> is it possible to use MySql or Postgres or another RDBMS instead of MongoDb?

Sure. Just re-write all the models.
