### ISSUE TITLE
Setup.js code not executing when in docker container

### ISSUE THREAD

**Issue by ROODAY** [jedireza/frame#167]
After porting our project to docker, we tried running the setup.js file inside of a docker-run.sh, however only the first few lines execute. Even independent console.logs don't fire. Here's a snippet of the top of the file:

```
console.log("Env: " + process.env.NODE_ENV);

console.log("about to enter if")
if (process.env.NODE_ENV === 'docker') {
  console.log("inside if")
  ...
  console.log("created root user details inside docker env")
};
```

The only thing that fires is the first line, no idea why even the second console.log doesn't fire.

**Comment by jedireza** [comment]
Thanks for opening an issue. I have not tried using docker so I won't be much of a help. Please update this issue if/when you resolve the issue.
