### ISSUE TITLE
Json Web Token Support

### ISSUE THREAD

**Issue by torabian** [jedireza/frame#172]
Meanwhile this library is awesome, I couldn't figure out if I can use JSON webtoken for my authentications. I want to deploy this app separately, and then generate web token with user logs in. On the other hand, on my own api, I want be able to unlock token without accessing this repository, by opening that token.
In fact, I'll check if the token is valid on the other repository, since I don't have "Revoke tokens" feature.
Hence, I've added this feature in my branch, and not sure weather I send a PR for this repo or not.

**Comment by jedireza** [comment]
I found some JWT plugins on the hapijs website: https://hapijs.com/plugins

Specifically these two:

 - https://www.npmjs.com/package/hapi-auth-jwt
 - https://www.npmjs.com/package/hapi-auth-jwt2

I'm not sure about your other goals, but using JWT with a hapi server ... 👍 .
