### ISSUE TITLE
PR for Swagger?

### ISSUE THREAD

**Issue by richardzyx** [jedireza/frame#174]
It took some repetitive work to add Swagger with hapi-swagger but the documentation is richer and more interactive than hapi docs. If you think it's a feature that's desirable and can be integrated into frame ecosystem, I'm happy to work on a small PR over the weekend. Hopefully someone will also find it helpful, and frame can get more momentum with Swagger support out of the box.

Thanks!

**Comment by bmgdev** [comment]
@richardzyx  YES! That'd be fantastic and hugely valuable. Thank you immensely.

**Comment by jedireza** [comment]
I'd love to see a PR for that.

**Comment by richardzyx** [comment]
Awesome. I already have the code just need some clean up. Will do it over the weekend. Thanks!

**Comment by richardzyx** [comment]
PR is up. Closing this issue.
