### ISSUE TITLE
Add SSL/TLS, .gitignore, Hapi Logging?

### ISSUE THREAD

**Issue by richardzyx** [jedireza/frame#177]
Following #176 #175 I would like to discuss adding the following features:

- SSL/TLS config files for production env. Right now it's particularly difficult with the bug in Confidence and loading large TLS files.
- A more complete .gitignore file
- Basic hapi logging? I personally find there to be a lack of documentation on best practices for Hapi logging. #34 has something and the same argument still applies. Will logging to console be a better option?

Thanks!

**Comment by jedireza** [comment]
Thanks for opening an issue.

> SSL/TLS config files for production env.

From my experience it's always been easier to terminate SSL before sending requests to the app. Like at a load balancer (aws, heroku, etc...). Maybe create a wiki page for manual/custom tls/ssl certificates. This shouldn't be baked-in by default.

> A more complete .gitignore file

This is highly subjective and best left to people customizing their apps. One size definitely does't fit all.

> Basic hapi logging? I personally find there to be a lack of documentation on best practices for Hapi logging. #34 has something and the same argument still applies. Will logging to console be a better option?

I started using `good` more recently and I like it a lot. It's definitely a step up from the default logging we get with hapi. I'd be ok with adding this to frame and removing the debug server configuration.

**Comment by richardzyx** [comment]
> From my experience it's always been easier to terminate SSL before sending requests to the app. Like at a load balancer (aws, heroku, etc...). 

I remember running into an issue specifically with TLS, but I see your point. 

> This is highly subjective and best left to people customizing their apps.

Ok

> I'd be ok with adding this to frame and removing the debug server configuration.

Sounds good. I've been using pm2 and graylog so my production logging setup is somewhat strange. I am actively looking for a better pattern, so I will leave this to someone else and establish a standard `good` logging. My basic implementation was included in #175
