### ISSUE TITLE
just question

### ISSUE THREAD

**Issue by tavousi** [jedireza/frame#187]
hi
why in 'server/models' folder we have status-entry.js ? we just use a little schema in it to use in status.js ? that's it ? just for more order ? or anything else ...
thank you

**Comment by jedireza** [comment]
The idea would be to also use that same schema in other models like we do in the Account model:

 - https://github.com/jedireza/frame/blob/8c83177b2d6aef3e3e0b16c2dd25c69aa8d62d68/server/models/account.js#L55-L58
