### ISSUE TITLE
Add Hapi-Auth-Cookie authentication support

### ISSUE THREAD

**Issue by gregfrasco** [jedireza/frame#191]
I have code that I could add to support Hapi-Auth-Cookie and JWTs. Would you be interested in a pull request? One for Hapi-Auth-Cookies and a different one for JWTs.

**Comment by jedireza** [comment]
Thanks for opening an issue and pardon the late reply. [Aqua](https://github.com/jedireza/aqua) also uses `hapi-auth-cookie`.

I don't think it's necessary to add different strategies by default since they're meant to be configured as needed and basic http is generic enough for a boilerplate.
