### ISSUE TITLE
is it useful ?

### ISSUE THREAD

**Issue by tavousi** [jedireza/frame#196]
user just want to login with new or old his session ! Omm there is a route to revoked session, why just not delete !! for saving history or something like that ?!!
https://github.com/jedireza/frame/blob/9e5a5b99f1eb79864a575459dbfff3abd4b6b60d/server/api/login.js#L131

**Comment by jedireza** [comment]
It could be useful. This was done in https://github.com/jedireza/frame/pull/182.
