### ISSUE TITLE
Api doc is unavailable

### ISSUE THREAD

**Issue by sashrika** [jedireza/frame#211]
Dear Community,

@jedireza   There was a nice API endpoint page which listed down all the REST endpoint is not unavailable. I think it was available at https://getframe.herokuapp.com/docs. Could you please fix this issue, or give us a link where we can access all the REST endpoints? 

Thank you!

**Comment by jedireza** [comment]
`lout` is what provided these docs. Looks like it's still being worked on for hapi 17 support: https://github.com/hapijs/lout/issues/175

**Comment by sashrika** [comment]
@jedireza there is a pull request, but it is still not merged with the master. Could you please tell me whether you have hosted the api document somewhere? Because it was very useful rather than going through the server.js files and understand the api.
