### ISSUE TITLE
No documentation on the 50 endpoints across 11 categories included in this user API starter

### ISSUE THREAD

**Issue by fishmongr** [jedireza/frame#215]
Hey Reza,

Great resource, thanks for your efforts on this! I'm looking to incorporate this into a project but am finding I have to reverse engineer your project to figure out what does what. 

It's awesome that all your endpoints automatically get interactive swagger documentation generated and deployed at /documentation but none of the huge amount of endpoints seem to have any descriptions or documentation at all. The endpoints nor any of the parameters for them. Am I missing something here?  The only information to be gleaned is purely on naming conventions in your endpoint list. 

Could you add descriptions to the endpoints and params via your Joi object schema so they'll be picked up by the swagger documentation? I figure that would take less than an hour and add huge value to anyone trying to get off the ground with this quickly. If it's a security thing even a comment in the code for each endpoint or just an external outline here on the Wiki link would be helpful. 

Thanks,
Mark

**Comment by jedireza** [comment]
There's a swagger json endpoint here: https://getframe.herokuapp.com/swagger.json

**Comment by jedireza** [comment]
You could also use something like [`lout`](https://github.com/hapijs/lout), which used to be included by default, but was removed since it was lacking hapi v17 support (though it looks like that was updated at the end of February).

**Comment by fishmongr** [comment]
Hi Reza,

Thanks, but i’m already familiar with that Swagger file, the problem I’m talking about actually has to do with that file and what it’s missing.

As you know, Swagger.json is generated by Hapi-Swagger and is meant to be displayed in Swagger UI. By default Hapi-Swagger even publishes your Swagger.json in it’s hosted copy of Swagger UI at /documentation of your deploy.

So for your deployed sample the interactive version of your Swagger.json file is available here: 
https://getframe.herokuapp.com/documentation

But if you compare that documentation to any other Swagger project documentation out there, like Swagger’s own example:

http://petstore.swagger.io

You’ll notice your docs look empty and not very usable. That’s because your Swagger.json file has no endpoint or parameter descriptions. This isn’t a problem if there are only a couple of endpoints but you have around 50 configurable endpoints with many similar names and parameters.

I’d be happy to start pushing pull requests to fill out title/description meta data in your Joi object schema as I start using these endpoints but likely won’t be using half of them (though I’m happy they are there, very robust).

Would you be able to take a pass at filling out the Joi object metadata tags for your endpoints and parameters? Or if you can just outline it in a doc I can make the updates. Then folks will stop bugging you for documentation, I believe this is what they all have been asking for, just some basic context around what each endpoint and parameter is for.

**Comment by jedireza** [comment]
> I’d be happy to start pushing pull requests to fill out title/description meta data in your Joi object schema as I start using these endpoints but likely won’t be using half of them (though I’m happy they are there, very robust).

Yeah if you could provide an example or two of the changes you'd make via a PR, I'd love to see them.

🙏Thanks for getting involved.

**Comment by fishmongr** [comment]
No problem, happy to support. Will have one out tomorrow 👌

**Comment by fishmongr** [comment]
Done! Pull request #217 
Let me know what you think and if there is anything else I can help with. I'll be continuing to grok the endpoints for my project in the meantime.
