### ISSUE TITLE
Purpose of status model should be documented

### ISSUE THREAD

**Issue by fishmongr** [jedireza/frame#219]
After studying the Frame project for awhile I got a good understanding of how everything works. I created a pull request documenting a lot of the tricky things in updated Swagger docs. 

One thing I haven't been able to figure out is what "status" is for. I went to the defunct Aqua project and found this great overview of what this is used for and what "pivot" is all about here:
https://github.com/jedireza/aqua/issues/227

I think it can be very useful if folks understand how it was designed. That explanation is great, perhaps it could be added to a dedicated wiki page in the Frame project?

**Comment by jedireza** [comment]
> I think it can be very useful if folks understand how it was designed. That explanation is great, perhaps it could be added to a dedicated wiki page in the Frame project?

Sounds good to me.
