### ISSUE TITLE
Swagger Issues

### ISSUE THREAD

**Issue by bmgdev** [jedireza/frame#220]
I'm just now getting around to upgrade to the latest release.  I'm able to hit "/documentation" ok (see screenshot) and swagger.json looks ok.  However, has anyone else noticed:

1) all calls to unauthenticated swagger endpoints (at /documentation) return 500s (not the typical 401) through Swagger UI
2) there is no Swagger input box/button to enter a Basic authorization header in typical Swagger fashion.

It would appear this last release is broken unless I'm missing something glaringly obvious here?

Also @jedireza I thank you for finally adding Swagger and ditching Lout.

![2018-06-04_23-14-32](https://user-images.githubusercontent.com/1637668/40959150-b1fdb66a-6850-11e8-9ed4-a96151790ea3.png)

**Comment by bmgdev** [comment]
Btw, I get 401s ok through Postman.  Somethings up with Swagger UI, wondering if older build? 

hapi@17.2.0
hapi-swagger@9.1.1
hapi-auth-basic@5.0.0

Attaching log

![2018-06-04_23-51-49](https://user-images.githubusercontent.com/1637668/40959766-8c07a090-6852-11e8-85bd-4da30a92d8bb.png)

**Comment by bmgdev** [comment]
Testing through Postman, I get 401s ok, but get 500s through Swagger UI. 

hapi@17.2.0
hapi-swagger@9.1.1
hapi-auth-basic@5.0.0

Log attached

![2018-06-04_23-51-49](https://user-images.githubusercontent.com/1637668/40960071-77f432fc-6853-11e8-90ff-edadcecd79dc.png)

**Comment by bmgdev** [comment]
Am noticing this issue on Authorization header not being passed: https://github.com/glennjones/hapi-swagger/issues/495  -- seems like a versioning issue? Can anyone confirm?

**Comment by fishmongr** [comment]
One thing it could be, I don't recall if Frame comes with this stock like Aqua but:
https://github.com/jedireza/aqua/wiki/HTTP-403-forbidden-when-accessing-API-endpoints

Also I noticed Swagger

**Comment by jedireza** [comment]
I don't have much time to debug this, but something I noticed on the live demo is the URL being used isn't right. This is probably Heroku's internal hostname and port.

<img width="974" alt="screen shot 2018-06-05 at 21 24 50" src="https://user-images.githubusercontent.com/979929/41016917-32b96586-6907-11e8-8bdf-220d4e69446f.png">

**Comment by bmgdev** [comment]
@fishmongr thanks for the help here. It turns out it doesn't seem to matter using .local vs localhost.  In any case I've added the server.ext as described in the post (now returning localhost urls).

@jedireza if you ran this locally I assume you'd get the same 500s as me with basic auth.

I dug in a bit deeper and found an easy solution for Swagger UI that can be use for basic or bearer auth. 'headers' need to be added to 'validate' on each route.  If you add the 'authorization' header, you'll get an input box to place a basic or bearer token from your login.  See image:

```
                headers: Joi.object({
                    'authorization': Joi.string().required()
                }).unknown()
```

For auto adding the authorization header, Swashbuckle for Swagger seems to do the trick, however the above solution is a low friction "fix" for now.  Let me know if you want a PR on this.

![2018-06-05_22-36-04](https://user-images.githubusercontent.com/1637668/41018933-3df0d6dc-6911-11e8-95e7-3e3fef4589ab.png)

![2018-06-05_22-39-59](https://user-images.githubusercontent.com/1637668/41018954-6695ac34-6911-11e8-90e0-5f7cf0e57d30.png)

**Comment by bmgdev** [comment]
ok gents, I found a global fix for Basic (or Bearer, JWT, etc) using the header api_key input box.  To get the global input box to show, need to add securityDefinitions for Basic.  The same below can also be applied for JWT (don't pay any attention to the hapi-swagger comment in source that says this is broken):

```                plugin:'hapi-swagger',
                options: {
                    securityDefinitions: {
                        'basic': {
                            'type': 'apiKey',
                            'name': 'Authorization',
                            'in': 'header'
                        }
                    },
                    security: [{ 'basic': [] }],
                    info: {
                        title: 'Frame API Documentation',```

and voila:

![2018-06-05_23-33-20](https://user-images.githubusercontent.com/1637668/41020748-dd4910e4-6918-11e8-8dae-ea70fecef3e4.png)

You can still use the method in the post above to protect by route, but ill stick to the global input box.

**Comment by bmgdev** [comment]
oi.  I just now noticed there are no route params setup so we can pass ids through swagger.   We need to do, for example:

```
    server.route({
        method: 'GET',
        path: '/api/accounts/{id}',
        options: {
            tags: ['api','accounts'],
            description: 'Get a customer account by ID. [Admin Scope]',
            notes: 'Get a customer account by ID.',
            validate: {
                params: {
                    id : Joi.number()
                            .required()
                            .description('the id to get the account'),
                }
            },
            auth: {
                scope: 'admin'
            }
        },
```

Attached is what it should look like in Swagger.  I need to fix all these anyway so look for the next PR.

![2018-06-06_00-25-35](https://user-images.githubusercontent.com/1637668/41023136-5e72468e-6920-11e8-88b1-3da6b671ee4c.png)

**Comment by fishmongr** [comment]
Ah good find on the global route fix, I forgot about the global route defaults, nice. 

Regarding the missing Swagger route params, that is a very topical discussion. I actually submitted the last pull request that filled out all the doc, endpoint, and tag descriptions like 5 days ago here:
https://github.com/jedireza/frame/pull/218
Before that /documentation was a ghost town, so pleasure to have someone else jumping in here with Swagger updates on this important framework!

I had some earlier discussions with @jedireza here https://github.com/jedireza/frame/pull/217 about a number of Swagger updates including query parameter and response schema. He is on-board but doesn't have time to implement and also has some valid concerns with maintenance and clutter he mentioned there.

**Comment by bmgdev** [comment]
Happy to contribute, I've been around Frame for a while now.  Great job on the docs, looking solid.  

One note regarding docs... given the nature of hapi/frame, it'd be good to keep docs/comments in separate swagger yaml files if we're able to, otherwise we run the risk of bloated routes.  I've done this in vanilla swagger-ui but have not investigated this with hapi/frame.

As far as getting these query parameters in/fixed, Swagger is effectively broken without them.  If we really want to dial it in, we should figure out why hapi-swagger keeps throwing us this username/password box if hitting an endpoint with no auth... and then check on why debug likes throwing us 500s.  It doesnt help that hapi-swagger hasnt been updated in a while, I'll hit that repo next.

**Comment by bmgdev** [comment]
Pull request https://github.com/jedireza/frame/pull/222 for controlling id params through Swagger.

**Comment by jedireza** [comment]
> One note regarding docs... given the nature of hapi/frame, it'd be good to keep docs/comments in separate swagger yaml files if we're able to, otherwise we run the risk of bloated routes.

I'd like to see what this looks like.

**Comment by jedireza** [comment]
Can we close this since #221 landed?

**Comment by bmgdev** [comment]
works for me.
