### ISSUE TITLE
Question: non-hapi version?

### ISSUE THREAD

**Issue by lonix1** [jedireza/frame#226]
Please forgive the potentially rude question. Many blogs link to this boilerplate because it's really good. I've learned a lot going though it's code.

But I don't use hapi. Does anyone know of something equivalent for vanilla express? There are many many many boilerplates out there, but not nearly as  good as this or "aqua".

Do you know of something comparable for express?

**Comment by jedireza** [comment]
> Please forgive the potentially rude question.

No worries.

> Do you know of something comparable for express?

I don't personally. Unless you're trying to crank out many systems, I'd recommend using boilerplates like this as inspiration and implement what you like into a project/system that you own from top to bottom.

**Comment by lonix1** [comment]
Ahh, an answer from Mr Boilerplate himself! :smile: I see you made an express boilerplate years ago, but it's no longer relevant.

I'll borrow some ideas from this one then, thanks for your advice.
