### ISSUE TITLE
starting the server fails due to missing mongodb url in hapi-mongo-models

### ISSUE THREAD

**Issue by Kyii** [jedireza/frame#37]
hey jedireza,
great project! in the latest version starting the server fails due to missing mongodb url in hapi-mongo-models:

    TypeError: Cannot read property 'url' of undefined
    at Function.BaseModel.connect (frame/node_modules/hapi-mongo-models/lib/base-model.js:16:39)

the mongodb object is undefined at frame/node_modules/hapi-mongo-models/index.js:16:15

    BaseModel.connect(mongodb, function (err, db) {

if i hardcode it here, everything works like expected

**Comment by jedireza** [comment]
Thanks for creating an issue. Also glad to hear you like the project.

`hapi-mongo-models` get's configured in the manifest (which uses settings from the config file): https://github.com/jedireza/frame/blob/master/manifest.js#L34.

Did you run the setup script? 

```bash
$ npm run setup
```

**Comment by Kyii** [comment]
hey jedireza,
thank you for the fast response! 
it was my fault! i copied over my config.js from a prior frame version, which was without the config entry for the hapiMongoModels. damm... ;-)
