### ISSUE TITLE
server.auth.strategy vs connection.auth.strategy

### ISSUE THREAD

**Issue by jardakotesovec** [jedireza/frame#38]
Just going through the source code to familiarize more with the project. Its looks really great!

Noticed one small thing:
https://github.com/jedireza/frame/blob/master/server/auth.js#L9
You are using connection.auth.strategy, I don't think you are supposed to use connection api directly as it is hidden behind server api. So I think it should be just server.auth.strategy and it will be applied for all connections for you.

**Comment by jedireza** [comment]
Thanks! I think you're right, this should get updated.
