### ISSUE TITLE
hapi-auth-basic vs hapi-auth-cookie

### ISSUE THREAD

**Issue by jardakotesovec** [jedireza/frame#39]
Just a question. 

I can see that hapi-auth-basic and hapi-auth-cookie provide very similar security level as you generate *password* per session for auth-basic. 

Also I see advantage that session model can be easily extended for additional data that are useful to keep in session, no need to use https://github.com/hapijs/yar for session data. 

So basically just wondering what was your thought process to go for basic-authentication. I can also see using auth-basic in frame as beneficial :-)..   just basically trying to make sure that I don't miss something as I considered hapi-auth-cookie as more common and secure option before.

**Comment by jardakotesovec** [comment]
Realized that in many cases its useful to manage sessions separately (like e-shops where you often don't need to authenticate).

Considering this fact..   I think both auth-basic and auth-cookie provides pretty much the same service. 

Still appreciate any insights why to pick one or the other. There might be something that I have not considered.

Thanks!

**Comment by jedireza** [comment]
I originally used `hapi-auth-basic` to experiment with authenticating requests where the server and client were not on the same machine. I ended up keeping it to be less assuming of what people would want by default.

I hope that answers your question.

**Comment by jardakotesovec** [comment]
Ok, thanks. Probably there is no obvious *better* choice, so I agree that it makes sense to let users to decide (basic vs cookie).
