### ISSUE TITLE
Clean up nested calls in User model test

### ISSUE THREAD

**Issue by fourq** [jedireza/frame#41]
https://github.com/jedireza/frame/blob/master/test/server/models/user.js#L142

**Comment by jedireza** [comment]
It's not a duplicate. The first one uses `username` and the second one uses `email`.

:+1: Thanks for bringing this up. We can clean this up and make it more obvious though (especially since we're already using `async` right there).

**Comment by fourq** [comment]
ahh! sorry, didn't catch that.

**Comment by fourq** [comment]
If you'd like I'll take this one and clean it up.

**Comment by jedireza** [comment]
:blush:
