### ISSUE TITLE
gmail configuration fix

### ISSUE THREAD

**Issue by kurtfm** [jedireza/frame#59]
https://github.com/jedireza/frame/wiki/Issues-using-Gmail-SMTP

Potential #3 
Setting in your Google Account>Signing In>Access for less secure apps

Set to 'Allowed' instead of 'Blocked'
![screen shot 2015-02-06 at 1 10 59 pm](https://cloud.githubusercontent.com/assets/2243297/6087541/b33f3902-ae01-11e4-8542-cd2f5160b63d.png)

**Comment by jedireza** [comment]
Thanks! Wiki has been updated:

https://github.com/jedireza/frame/wiki/Issues-using-Gmail-SMTP#potential-cause-3
