### ISSUE TITLE
Account is created but 500 error returned because SMTP failure

### ISSUE THREAD

**Issue by kurtfm** [jedireza/frame#60]
On /api/signup if nodemailer call fails to make the outbound mail send call the client gets a 500 error but the account was created.

Since the account was created this should return a successful response.

Suppose it gets tricky if you are requiring email confirmation... if the mailer fails should you NOT create and throw a generic error?

**Comment by jedireza** [comment]
Yes, I was thinking about this recently. It really does depend on how you want it to work in your app.

By default though, since we don't require email confirmation, if the email fails to send, we should just log a message (server side) and continue.
