### ISSUE TITLE
User and Account

### ISSUE THREAD

**Issue by taktran** [jedireza/frame#67]
I can see from the code, when you create a user, there is also an account that is created within the user model. The full name is stored in account and the username is stored in user.

What is the intention of the separation? It appears that a user would have multiple accounts, so say I want to add twitter/facebook logins, would the best way be to add these as accounts to the user?

Generally, when extending the codebase, what would you put in `User` and what would you put in `Account`?

Would love to have some documentation to clear this up =)

**Comment by jedireza** [comment]
Good question. I've added these wiki pages. Please post again if they don't address your questions.

 - [Users, Roles & Groups](https://github.com/jedireza/frame/wiki/Users,-Roles-&-Groups)
 - [Admin & Admin Group Permissions](https://github.com/jedireza/frame/wiki/Admin-&-Admin-Group-Permissions)

**Comment by taktran** [comment]
Ah thanks! That does make things clearer.

In my system, I didn't want `name` (first/middle/last), but did want `username`, so I was wondering whether I could delete `account` altogether. But seeing as `account` is part of the roles system, it doesn't seem that easy to remove. Not particularly a bad thing, just makes more sense why it's there now :smile:
