### ISSUE TITLE
Multiple logins/sessions

### ISSUE THREAD

**Issue by taktran** [jedireza/frame#70]
I've noticed that when you log in multiple times, the previous logins are removed and hence invalidated. This means that you can't log in from different locations. Is this intentional or just something left for the implementor to add?

It seems the invalidation happens in [`Session.create`](https://github.com/jedireza/frame/blob/master/server/models/session.js#L76-L84), where you clear out other sessions from the same user apart from the one just created.

It seems to make sense for when there is only 1 client for the api, but if there multiple clients, each login will invalidate the login of other clients. Just wondering what the rationale was for this?

Thanks!

**Comment by jedireza** [comment]
I'm glad you brought this up.

> I've noticed that when you log in multiple times, the previous logins are removed and hence invalidated. This means that you can't log in from different locations. Is this intentional or just something left for the implementor to add?

This is the intended _default_ behavior and something I expect developers to change in their implementations. You could easily change this to allow multiple devices or to allow shared sessions.

GitHub actually does a nice job at a feature like this. If you go to Accounts > Security, there is a session section that lists your sessions and even allows you to revoke them.

![screen shot 2015-02-22 at 9 10 47 am](https://cloud.githubusercontent.com/assets/979929/6319489/ed471e30-ba72-11e4-9198-8ced9570cb21.png)
