### ISSUE TITLE
Test Fails

### ISSUE THREAD

**Issue by callerc1** [jedireza/frame#73]
Hi,

After upgrading to the latest version of frame (v3.1.1) i'm having an issue when running `npm test` any ideas what this could be?

```
Failed tests:

  3) App it composes a server:

      Unknown authentication strategy: simple in path: /api/users
```

**Comment by callerc1** [comment]
looks like upgrading my node version fixes this was on v0.10.37 now v0.12.0. Which specific release had this requirement?

**Comment by jedireza** [comment]
Hmm. We're testing on `v0.10.x`, `v0.11.x` and `v0.12.x`. https://travis-ci.org/jedireza/frame

**Comment by jedireza** [comment]
Any updates?

**Comment by callerc1** [comment]
@jedireza Haven't had a chance to look into this some more. But hopefully next week.

**Comment by jedireza** [comment]
Closing for now. If you find out more, feel free to post them on this thread.
