### ISSUE TITLE
successful link/unlink handlers return empty

### ISSUE THREAD

**Issue by Kyii** [jedireza/frame#80]
hey jedireza,
i think the link/unlink handlers stated below don't return the result of the successful operation. they return just empty. if you wanted to return the updated account
    
    reply(results.account[0]) 

should be
    
    reply(results.account); 
   
    ---
    server.route({
        method: 'DELETE',
        path: options.basePath + '/accounts/{id}/user',

    server.route({
        method: 'PUT',
        path: options.basePath + '/accounts/{id}/user',

**Comment by jedireza** [comment]
Thanks for creating an issue and reporting the bug.
