### ISSUE TITLE
Rationale for indentation style in Models, and elsewhere?

### ISSUE THREAD

**Issue by williamle8300** [jedireza/frame#85]
Hi jedireza, thanks for building frame. I dig it!

I wanted to ask you, What's your rationale for the eccentric indentation style for stuff in the models folder, and functions in general? Everything is flattened, like statements inside functions and stuff... they're vertically aligned with the function definition, etc.

I like the stuff you make, and thought you may have some wisdom on why you do this.

**Comment by williamle8300** [comment]
Ah. Nevermind. My linting removed the indentations. My bad!

**Comment by jedireza** [comment]
I'm glad you enjoy the project. :smile:
