### ISSUE TITLE
Why are (most) endpoints pluralized?

### ISSUE THREAD

**Issue by williamle8300** [jedireza/frame#86]
I'm starting out trying to be a Legit Programmer, and I read some tutorials on how to design REST apis.

My question, Why are most of the endpoints pluralized? I get the impression that there aren't hard and fast rules, but it seems like people consider singular noun endpoints as the "right" way to do it. I'm thinking about reformulating your endpoints as singular nouns. I can send you a PR if you want for this.

More important, I'd like to hear your rationale behind this design decision.

**Comment by jedireza** [comment]
Thanks for creating an issue.

> Why are most of the endpoints pluralized? I get the impression that there aren't hard and fast rules...

You're right. There really aren't any rules written in stone. https://www.google.com/search?q=rest+apis+singular+or+plural

I guess my thought at the time was `/accounts` allows you to read the collection/list of accounts and `/accounts/:id` let's you read a specific account.

> I'm thinking about reformulating your endpoints as singular nouns. I can send you a PR if you want for this.

That's find if you want to do that for your project, I don't see a need to change Frame.
