### ISSUE TITLE
Why "admin role" for status updates?

### ISSUE THREAD

**Issue by williamle8300** [jedireza/frame#87]
Also, kinda related, I don't understand the meaning behind your usage of the word "pivot."

I saw how it's used in your `aqua` framework, and I assume it's the identical idea in `frame`. I get what it does, but the feature comes off a little weird to me. Can you elaborate on it?

**Comment by jedireza** [comment]
Thanks for asking. It simply allows us to use one collection instead of creating multiple that are essentially identical.
