### ISSUE TITLE
Why not replace Frame's backend with Aqua's backend?

### ISSUE THREAD

**Issue by williamle8300** [jedireza/frame#91]
It looks like there's a hanging PR for /api/logout

I'm just wondering, Why not just gut the frontend from Aqua, and drop it into Frame?

All the tests are passing for Aqua I presume.

**Comment by jedireza** [comment]
Aqua started with Frame as the base. Besides the open PR they should be almost identical. There may be some really minor differences ([like the `baseUrl`](https://github.com/jedireza/aqua/blob/master/config.example#L20-L25)) that help support the front-end experience.

**Comment by williamle8300** [comment]
I still don't see why Aqua's backend isn't dropped into Frame...? It seems like a simple matter to me.

**Comment by jedireza** [comment]
You mean to fix resolve the open PR?

**Comment by williamle8300** [comment]
No. I assume the tests are passing for Aqua. This means you can close that PR if you drop in the Aqua backend.

Does this makes sense?

**Comment by jedireza** [comment]
Resolving the open PR will put them back in line. Otherwise I'm not sure I follow.

**Comment by williamle8300** [comment]
It seems to me if Frame is being touted as the backend which Aqua is built upon, it would make sense that the backend would be identical.

For me, I don't understand how a rationale can be made to not drop in the Aqua framework. Either that, or drop the Frame backend into Aqua.

**Comment by jedireza** [comment]
The current PR isn't getting much attention at the moment. If you'd like to create a PR to align them I'd be happy to review it.

**Comment by williamle8300** [comment]
I understand that putting a PR through will patch up Frame nicely. That's not in question for me at all.

Why I don't get is why you're not answering my question:

"If Frame is being touted as the backend which Aqua is built upon, it would make sense that the backend would be identical."

Why is it not identical?

**Comment by williamle8300** [comment]
Please give me an answer to this question @jedireza.

**Comment by jedireza** [comment]
> Aqua started with Frame as the base. Besides the open PR they should be almost identical. There may be some really minor differences ([like the `baseUrl`](https://github.com/jedireza/aqua/blob/master/config.example#L20-L25)) that help support the front-end experience.

Since they are different code bases they need to maintained separately. When a change in Aqua should be made in Frame, it's a manual change that needs to be done. And it looks like the login patch was missed.
