### ISSUE TITLE
.takeover() vs Boom

### ISSUE THREAD

**Issue by taktran** [jedireza/frame#95]
Just wondering, why do you use `.takeover().code(400)` over `Boom.badRequest('...')` in pre blocks eg, https://github.com/jedireza/frame/blob/master/server%2Fapi%2Flogin.js#L81-L83

It seems like it's not consistent with how the API spits out errors.

**Comment by jedireza** [comment]
Thanks for creating an issue. I'd be fine with using `Boom`, especially if it's more consistent with other hapi coding conventions.

**Comment by jedireza** [comment]
I'm still looking into using Boom, but wanted to note why `reply().takeover()` is important inside of route prerequisites:

> Note that prerequisites do not follow the same rules of the normal reply interface. In all other cases, calling `reply()` with or without a value will use the result as the response sent back to the client. In a prerequisite method, calling `reply()` will assign the returned value to the provided `assign` key. If the returned value is an error, the `failAction` setting determines the behavior. __To force the return value as the response and ends the request lifecycle, use the `reply().takeover()` method.__

Souce: http://hapijs.com/api#route-prerequisites

**Comment by jedireza** [comment]
The syntax using Boom is much better. Thanks for bringing this up.

**Comment by taktran** [comment]
Thanks for updating!

Great work keeping it so up to date! :rocket: =)
