### ISSUE TITLE
Should model validation happen by default?

### ISSUE THREAD

**Issue by taktran** [jedireza/frame#98]
We've noticed on a project using frame that the tests don't deal with the case where validations on the model schema fail (eg, [user schema](https://github.com/jedireza/frame/blob/master/server/models/user.js#L73-L94). This lead us to find out, that [hapi-mongo-models](https://github.com/jedireza/hapi-mongo-models) doesn't seem to validate by default when creating/updating, although there is a [validate](https://github.com/jedireza/hapi-mongo-models#validateinput-callback) function.

An example is in [user.js](https://github.com/jedireza/frame/blob/master/server/models/user.js#L143), the `insertOne` wouldn't fail if the [schema validation](https://github.com/jedireza/frame/blob/master/server/models/user.js#L73-L94) failed.

Is this intended? Are the API endpoints supposed to catch all the validation errors in frame? Is validation in `hapi-mongo-models` supposed to be left up to the user of the library to deal with before persisting to the mongo layer? Have I missed something blatantly obvious? ;)

**Comment by jedireza** [comment]
Thanks for opening an issue.

> Is this intended?

Yes. The `validate` functionality is there if you choose to use it, but not used automatically.

> Are the API endpoints supposed to catch all the validation errors in frame?

Currently the validation we do in the routes is to determine that we've received the expected values.

For example: https://github.com/jedireza/frame/blob/bb995b6a98d1394668f5431ba992c81a31ac8d9a/server/api/users.js#L19-L29

> Is validation in `hapi-mongo-models` supposed to be left up to the user of the library to deal with before persisting to the mongo layer?

Yes. You'll have to handle a model schema failure in your `handler` or a `pre` and determine how to communicate that with the user.

> Have I missed something blatantly obvious? ;)

Nope. :grin:
